[application]
nodeURL = "http://34.75.159.76:4545"
contractAddress = "0xA5DD67c2F23E7e3F13Cc704d399f8F63e77958aE"
accountContractAddress = "0x1CaFf993d5f0053156761682263c1614c7C37D7C"
nodeKeyPath = "/root/lacchain/data/key"  
nodeAddressPath = "/root/lacchain/data/nodeAddress"
port = 9001

[keystore]
agent = "/home/adrian/.ethereum/keystore/UTC--2020-06-26T19-00-23.241896464Z--bceda2ba9af65c18c7992849c312d1db77cf008e"

[passphrase]
agent = "Peru123."